### ISSUE TITLE
Unexpected error: <class 'TypeError'>

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/k8-data-visualization#78] opened 2020-09-23 10:59 UTC
![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/bed0a538-ec1e-4532-ac00-dc6019ae2851)

Hi
Can you please check why is this throwing an error?

**config.json**
![image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/21e85e5e-7367-4bdc-a1a6-0f85cc6d98ef)

**Comment by lucia15** [comment] 2020-09-30 11:22
It seems that the problem is related to Github limiting the API requests by IP address. Apparently if you use username and token you get more requests, so I have modified the code to include credential information and to display an error message whenever the number of requests are out. I think that will solve the problem, but I still have to PR it.

**Comment by GiuseMSD** [comment] 2020-09-30 12:02
Yes, Github API limit can be the reason.

**Comment by lucia15** [comment] 2020-09-30 15:03
Ok, I will PR this modification soon

**Comment by GiuseMSD** [comment] 2020-10-02 10:22
This is because of API limitation. fixed by another issue together.

**Closed by GiuseMSD** 2020-10-02 10:22 UTC
Labels: bug
